<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto

namespace Protobuf\Prots;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>protobuf.prots.MailConfig</code>
 */
class MailConfig extends \Google\Protobuf\Internal\Message
{
    /**
     *发件人
     *
     * Generated from protobuf field <code>string to = 1;</code>
     */
    private $to = '';
    /**
     *收件人
     *
     * Generated from protobuf field <code>string from = 2;</code>
     */
    private $from = '';
    /**
     *内容
     *
     * Generated from protobuf field <code>string msg = 3;</code>
     */
    private $msg = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $to
     *          发件人
     *     @type string $from
     *          收件人
     *     @type string $msg
     *          内容
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common::initOnce();
        parent::__construct($data);
    }

    /**
     *发件人
     *
     * Generated from protobuf field <code>string to = 1;</code>
     * @return string
     */
    public function getTo()
    {
        return $this->to;
    }

    /**
     *发件人
     *
     * Generated from protobuf field <code>string to = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTo($var)
    {
        GPBUtil::checkString($var, True);
        $this->to = $var;

        return $this;
    }

    /**
     *收件人
     *
     * Generated from protobuf field <code>string from = 2;</code>
     * @return string
     */
    public function getFrom()
    {
        return $this->from;
    }

    /**
     *收件人
     *
     * Generated from protobuf field <code>string from = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setFrom($var)
    {
        GPBUtil::checkString($var, True);
        $this->from = $var;

        return $this;
    }

    /**
     *内容
     *
     * Generated from protobuf field <code>string msg = 3;</code>
     * @return string
     */
    public function getMsg()
    {
        return $this->msg;
    }

    /**
     *内容
     *
     * Generated from protobuf field <code>string msg = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setMsg($var)
    {
        GPBUtil::checkString($var, True);
        $this->msg = $var;

        return $this;
    }

}

