<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto

namespace GPBMetadata;

class Common
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a8e010a0c636f6d6d6f6e2e70726f746f120e70726f746f6275662e7072" .
            "6f747322330a0a4d61696c436f6e666967120a0a02746f18012001280912" .
            "0c0a0466726f6d180220012809120b0a036d736718032001280922310a07" .
            "50657273696f6e120c0a046e616d65180120012809120b0a036167651802" .
            "20012805120b0a03736578180320012805620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

